---
version: 2
plan:
  project-key: CUM
  key: CD
  name: Cumulus Dashboard
stages:
- Build SPEC Dashboard:
    manual: false
    final: false
    jobs:
    - Create tarball
- Clean Up:
    manual: false
    final: false
    jobs:
    - Clean Up
Create tarball:
  key: CST
  tasks:
  - script:
      interpreter: SHELL
      scripts:
      - |-
        #!/bin/sh

        set -evx

        find . -mindepth 1 -maxdepth 1 -exec rm -rf {} \;
  - checkout:
      path: cumulus-dashboard
      force-clean-build: 'false'
  - command:
      executable: tar
      argument: -cvzf cumulus-dashboard.tgz cumulus-dashboard
  artifacts:
  - name: cumulus-dashboard.tgz
    pattern: cumulus-dashboard.tgz
    shared: true
    required: false
Clean Up:
  key: SRC
  tasks:
# Checkout Task will be added implicitly during Specs import
  - script:
      interpreter: SHELL
      scripts:
      - |
        find . -mindepth 1 -maxdepth 1 -exec rm -rf {} \;
  artifacts:
  - name: straw report
    pattern: straw_report.txt
    shared: true
    required: false
variables:
  EECS_PROFILE: cumulus
triggers:
- polling: 180
branches:
  create: for-new-branch
  delete:
    after-deleted-days: 7
    after-inactive-days: 30
  link-to-jira: true
notifications:
- events:
  - plan-failed
  recipients:
  - committers
labels:
- aws-cli
- cloudformation
other:
  concurrent-build-plugin: system-default
---
version: 2
plan:
  key: CUM-CD
plan-permissions:
- users:
  - mhuffnagle
  - pquinn
  groups:
  - bamboo-cumulus-dev
  permissions:
  - view
  - edit
  - build
  - clone
  - admin
- users:
  - scisco
  permissions:
  - view
  - build
...
