version: "3"
services:
  elasticsearch:
    image: elasticsearch:5.6
    network_mode: "service:shim"
    environment:
      ES_JAVA_OPTS: "-Xms750m -Xmx750m"
  localstack:
    image: localstack/localstack:0.10.7
    network_mode: "service:shim"
    environment:
      SERVICES: "kinesis,lambda,s3,sns,sqs,dynamodb,cloudwatch,cloudwatchlogs,stepfunctions"
      DATA_DIR: "/tmp/localstack/data"
  shim:   # empty container to open ports
    image: node:10.16.3
    command:
      bash -c "tail -f /dev/null"
    working_dir:
      /cumulus-dashboard
    volumes:
      - ../:/cumulus-dashboard:cached
    ports:
      - "9200:9200"
      - "4550-4586:4550-4586"
