version: "3"
services:
  elasticsearch:
    image: elasticsearch:5.6
    network_mode: "service:build_env"
    environment:
      ES_JAVA_OPTS: "-Xms750m -Xmx750m"
  localstack:
    image: localstack/localstack:0.8.10
    network_mode: "service:build_env"
    environment:
      SERVICES: "kinesis,lambda,s3,sns,sqs,dynamodb,cloudwatch,cloudwatchlogs"
  build_env:
    image: jlkovarik/cumulus_build_env:1
    volumes:
      - ../:/source/cumulus
    environment:
      - LOCALSTACK_HOST=127.0.0.1
      - LOCAL_ES_HOST=127.0.0.1
      - CI_UID
      - bamboo_planKey
    command: tail -f /dev/null
